# Site settings
title: callumd.com
email: cdd@callumd.com
description: > # this means to ignore newlines until "baseurl:"
    Thoughts, musings, and scrablings from inside my head. Mostly pertaining to tech.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://callumd.com" # the base hostname & protocol for your site
twitter_username: callumd
github_username:  callumd789

# Build settings
markdown: kramdown
